/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import DAO.EventoDAO;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Evento;

/**
 *
 * @author yosoy
 */
public class ventCrearEvento extends javax.swing.JFrame {

    EventoDAO edao = new EventoDAO();

    /**
     * Creates new form ventCrearEvento
     */
    public ventCrearEvento() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pack();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCrearEvento = new javax.swing.JPanel();
        lCrear = new javax.swing.JLabel();
        lTitulo = new javax.swing.JLabel();
        tTituloEvento = new javax.swing.JTextField();
        lDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        lUbicacion = new javax.swing.JLabel();
        tUbicacion = new javax.swing.JTextField();
        dcFecha = new com.toedter.calendar.JDateChooser();
        lFecha = new javax.swing.JLabel();
        lCapacidad = new javax.swing.JLabel();
        tCapacidad = new javax.swing.JTextField();
        lTipo = new javax.swing.JLabel();
        cbTipoEvento = new javax.swing.JComboBox<>();
        bCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lCrear.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        lCrear.setText("CREAR EVENTO");

        lTitulo.setText("Titulo del Evento:");

        lDescripcion.setText("Descripcion breve:");

        taDescripcion.setColumns(20);
        taDescripcion.setRows(5);
        jScrollPane1.setViewportView(taDescripcion);

        lUbicacion.setText("Ubicación:");

        lFecha.setText("Fecha:");

        lCapacidad.setText("Capacidad Máxima:");

        tCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCapacidadActionPerformed(evt);
            }
        });

        lTipo.setText("Tipo de Evento:");

        cbTipoEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deportivo", "Cultural", "Cumpleaños", "Boda", "Musical", "Bautizo", "Comunion" }));

        bCrear.setText("Crear");
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCrearEventoLayout = new javax.swing.GroupLayout(pCrearEvento);
        pCrearEvento.setLayout(pCrearEventoLayout);
        pCrearEventoLayout.setHorizontalGroup(
            pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCrearEventoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lCrear)
                .addGap(125, 125, 125))
            .addGroup(pCrearEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCrearEventoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tTituloEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pCrearEventoLayout.createSequentialGroup()
                        .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lDescripcion)
                            .addComponent(lUbicacion)
                            .addComponent(lFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lCapacidad)
                            .addComponent(lTipo))
                        .addGap(18, 18, 18)
                        .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(tUbicacion)
                            .addComponent(tCapacidad)
                            .addComponent(cbTipoEvento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pCrearEventoLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(bCrear)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        pCrearEventoLayout.setVerticalGroup(
            pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCrearEventoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lCrear)
                .addGap(46, 46, 46)
                .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tTituloEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTitulo))
                .addGap(18, 18, 18)
                .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lDescripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUbicacion)
                    .addComponent(tUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFecha))
                .addGap(31, 31, 31)
                .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCapacidad)
                    .addComponent(tCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTipo)
                    .addComponent(cbTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(bCrear)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pCrearEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pCrearEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCapacidadActionPerformed
        // TODO add your handling code here:

        String capacIntroducida = tCapacidad.getText(); // Asumiendo que tCapacidad es tu JTextField
        try {
            int capacidad = Integer.parseInt(capacIntroducida); // Intenta convertir el texto a entero
            if (capacidad < 0) {
                JOptionPane.showMessageDialog(null, "Introduce un número positivo.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (capacidad > 1000) {
                JOptionPane.showMessageDialog(null, "La capacidad máxima no puede exceder de 1000.", "Límite excedido", JOptionPane.WARNING_MESSAGE);
            } else {
                // Aquí puedes seguir con el código si el número es válido y está en el rango permitido
                System.out.println("Capacidad establecida a " + capacidad);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, introduce un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_tCapacidadActionPerformed

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        // TODO add your handling code here:
        // Recoger los datos del formulario
        String titulo = tTituloEvento.getText();
        String descripcion = taDescripcion.getText();
        String ubicacion = tUbicacion.getText();
        Date fecha = dcFecha.getDate();  // Esto recoge la fecha del JDateChooser
        String capacidadStr = tCapacidad.getText();
        String tipoEvento = (String) cbTipoEvento.getSelectedItem();

        if (titulo.isEmpty() || descripcion.isEmpty() || ubicacion.isEmpty() || fecha == null || capacidadStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return;  // Detiene la ejecución si algún campo necesario está vacío
        }

        int capacidad;
        try {
            capacidad = Integer.parseInt(capacidadStr);
            if (capacidad <= 0 || capacidad > 1000) {
                JOptionPane.showMessageDialog(this, "La capacidad debe ser un número positivo menor o igual a 1000.", "Error en la capacidad", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, introduce un número válido para la capacidad.", "Error en la capacidad", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear el objeto evento
        Evento evento = new Evento();
        evento.setTituloEvento(titulo);
        evento.setDescripcion(descripcion);
        evento.setUbicacion(ubicacion);
        evento.setFecha(fecha);
        evento.setCapacidadMax(capacidad);
        evento.setTipoEvento(tipoEvento);

        // Insertar el evento usando el método de la clase DAO
        try {
            edao.insertarEvento(evento);
            JOptionPane.showMessageDialog(this, "Evento creado con éxito!", "Evento Creado", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al crear el evento: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_bCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventCrearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventCrearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventCrearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventCrearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventCrearEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCrear;
    private javax.swing.JComboBox<String> cbTipoEvento;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCapacidad;
    private javax.swing.JLabel lCrear;
    private javax.swing.JLabel lDescripcion;
    private javax.swing.JLabel lFecha;
    private javax.swing.JLabel lTipo;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel lUbicacion;
    private javax.swing.JPanel pCrearEvento;
    private javax.swing.JTextField tCapacidad;
    private javax.swing.JTextField tTituloEvento;
    private javax.swing.JTextField tUbicacion;
    private javax.swing.JTextArea taDescripcion;
    // End of variables declaration//GEN-END:variables
}
