/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import DAO.EventoDAO;
import controlador.controlarJavaHelp;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import modelo.Evento;

/**
 *
 * @author yosoy
 */
public class ventActuEventos extends javax.swing.JFrame {

    private final EventoDAO edao = new EventoDAO();
    private final ventEventos ventEventos; // Referencia a la ventana padre
    private final int idEvento; // ID del evento a actualizar

    public ventActuEventos(ventEventos ventEventos, int idEvento, String titulo, String descripcion, String ubicacion, Date fecha, String tipoEvento) {
      
        this.ventEventos = ventEventos;
        this.idEvento = idEvento;
        initComponents();
        controlarJavaHelp.inicializarAyuda();
       
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pack();
        setResizable(false);
        setLocationRelativeTo(null);
        // Prefill fields
        tTituloEvento.setText(titulo != null ? titulo : "");
        taDescripcion.setText(descripcion != null ? descripcion : "");
        tUbicacion.setText(ubicacion != null ? ubicacion : "");
        dcFecha.setDate(fecha);
        tCapacidad.setText(""); // Capacidad no se muestra inicialmente; se deja al usuario
        cbTipoEvento.setSelectedItem(tipoEvento != null ? tipoEvento : "Deportivo");
        
            getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("F1"), "javahelp");
        getRootPane().getActionMap().put("javahelp", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controlarJavaHelp.mostrarAyuda();
            }
        });
        temporizador2.setBackground(Color.LIGHT_GRAY);
          temporizador2.setTextoNuevo("Cancelar");
        temporizador2.setTiempo(15);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCrearEvento = new javax.swing.JPanel();
        lCrear = new javax.swing.JLabel();
        lTitulo = new javax.swing.JLabel();
        tTituloEvento = new javax.swing.JTextField();
        lDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        lUbicacion = new javax.swing.JLabel();
        tUbicacion = new javax.swing.JTextField();
        dcFecha = new com.toedter.calendar.JDateChooser();
        lFecha = new javax.swing.JLabel();
        lCapacidad = new javax.swing.JLabel();
        tCapacidad = new javax.swing.JTextField();
        lTipo = new javax.swing.JLabel();
        cbTipoEvento = new javax.swing.JComboBox<>();
        bGuardarCambios = new javax.swing.JButton();
        temporizador2 = new ComponentePropio.Temporizador();
        mbAyuda = new javax.swing.JMenuBar();
        mAyuda = new javax.swing.JMenu();
        jmAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lCrear.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        lCrear.setText("ACTUALIZAR EVENTO");

        lTitulo.setText("Titulo del Evento:");

        lDescripcion.setText("Descripcion breve:");

        taDescripcion.setColumns(20);
        taDescripcion.setRows(5);
        jScrollPane1.setViewportView(taDescripcion);

        lUbicacion.setText("Ubicación:");

        lFecha.setText("Fecha:");

        lCapacidad.setText("Capacidad Máxima:");

        tCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCapacidadActionPerformed(evt);
            }
        });

        lTipo.setText("Tipo de Evento:");

        cbTipoEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deportivo", "Cultural", "Cumpleaños", "Boda", "Musical", "Bautizo", "Comunion" }));

        bGuardarCambios.setText("Guardar cambios");
        bGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarCambiosActionPerformed(evt);
            }
        });

        temporizador2.addCapturaListener(new ComponentePropio.Temporizador.CapturaListener() {
            public void capturarFinCuentaAtras(ComponentePropio.botonEvento evt) {
                temporizador2CapturarFinCuentaAtras(evt);
            }
        });

        javax.swing.GroupLayout pCrearEventoLayout = new javax.swing.GroupLayout(pCrearEvento);
        pCrearEvento.setLayout(pCrearEventoLayout);
        pCrearEventoLayout.setHorizontalGroup(
            pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCrearEventoLayout.createSequentialGroup()
                .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCrearEventoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pCrearEventoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tTituloEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pCrearEventoLayout.createSequentialGroup()
                                .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lDescripcion)
                                    .addComponent(lUbicacion)
                                    .addComponent(lFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lCapacidad)
                                    .addComponent(lTipo))
                                .addGap(18, 18, 18)
                                .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(tUbicacion)
                                    .addComponent(tCapacidad)
                                    .addComponent(cbTipoEvento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(pCrearEventoLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lCrear))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCrearEventoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(temporizador2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(bGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pCrearEventoLayout.setVerticalGroup(
            pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCrearEventoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lCrear)
                .addGap(37, 37, 37)
                .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tTituloEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTitulo))
                .addGap(18, 18, 18)
                .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lDescripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUbicacion)
                    .addComponent(tUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFecha))
                .addGap(31, 31, 31)
                .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCapacidad)
                    .addComponent(tCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTipo)
                    .addComponent(cbTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(pCrearEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardarCambios)
                    .addComponent(temporizador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        mAyuda.setText("Ayuda");

        jmAyuda.setText("JavaHelp");
        jmAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAyudaActionPerformed(evt);
            }
        });
        mAyuda.add(jmAyuda);

        mbAyuda.add(mAyuda);

        setJMenuBar(mbAyuda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pCrearEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pCrearEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCapacidadActionPerformed
        // TODO add your handling code here:

        String capacIntroducida = tCapacidad.getText();
        try {
            int capacidad = Integer.parseInt(capacIntroducida);
            if (capacidad < 0) {
                JOptionPane.showMessageDialog(null, "Introduce un número positivo.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (capacidad > 1000) {
                JOptionPane.showMessageDialog(null, "La capacidad máxima no puede exceder de 1000.", "Límite excedido", JOptionPane.WARNING_MESSAGE);
            } else {
                System.out.println("Capacidad establecida a " + capacidad);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, introduce un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_tCapacidadActionPerformed

    private void bGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarCambiosActionPerformed
        // Recoger los datos del formulario
        String titulo = tTituloEvento.getText().trim();
        String descripcion = taDescripcion.getText().trim();
        String ubicacion = tUbicacion.getText().trim();
        Date fecha = dcFecha.getDate();
        String capacidadStr = tCapacidad.getText().trim();
        String tipoEvento = (String) cbTipoEvento.getSelectedItem();

        // Validaciones básicas
        if (titulo.isEmpty() || descripcion.isEmpty() || ubicacion.isEmpty() || fecha == null || capacidadStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int capacidad;
        try {
            capacidad = Integer.parseInt(capacidadStr);
            if (capacidad <= 0 || capacidad > 1000) {
                JOptionPane.showMessageDialog(this, "La capacidad debe ser un número positivo menor o igual a 1000.", "Error en la capacidad", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, introduce un número válido para la capacidad.", "Error en la capacidad", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear el objeto evento
        Evento evento = new Evento();
        evento.setIdEvento(idEvento);
        evento.setTituloEvento(titulo);
        evento.setDescripcion(descripcion);
        evento.setUbicacion(ubicacion);
        evento.setFecha(fecha);
        evento.setCapacidadMax(capacidad);
        evento.setTipoEvento(tipoEvento);

        // Llamar al método DAO para actualizar el evento
        try {
            edao.actualizarEvento(evento);
            JOptionPane.showMessageDialog(this, "Evento actualizado con éxito.", "Evento Actualizado", JOptionPane.INFORMATION_MESSAGE);
            ventEventos.filtrarEventos(); // Refrescar la tabla en ventEventos
            this.dispose(); // Cerrar la ventana
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar el evento: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_bGuardarCambiosActionPerformed

    private void jmAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAyudaActionPerformed
        // TODO add your handling code here:
       controlarJavaHelp.mostrarAyuda();

    }//GEN-LAST:event_jmAyudaActionPerformed

    private void temporizador2CapturarFinCuentaAtras(ComponentePropio.botonEvento evt) {//GEN-FIRST:event_temporizador2CapturarFinCuentaAtras
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_temporizador2CapturarFinCuentaAtras

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventActuEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventActuEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventActuEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventActuEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventActuEventos(null, 0, "", "", "", null, "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardarCambios;
    private javax.swing.JComboBox<String> cbTipoEvento;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmAyuda;
    private javax.swing.JLabel lCapacidad;
    private javax.swing.JLabel lCrear;
    private javax.swing.JLabel lDescripcion;
    private javax.swing.JLabel lFecha;
    private javax.swing.JLabel lTipo;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel lUbicacion;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenuBar mbAyuda;
    private javax.swing.JPanel pCrearEvento;
    private javax.swing.JTextField tCapacidad;
    private javax.swing.JTextField tTituloEvento;
    private javax.swing.JTextField tUbicacion;
    private javax.swing.JTextArea taDescripcion;
    private ComponentePropio.Temporizador temporizador2;
    // End of variables declaration//GEN-END:variables
}
