/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;
import controlador.controlarJavaHelp;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author yosoy
 */
public class ventInformes extends javax.swing.JFrame {

    /**
     * Creates new form ventInformes
     */
    public ventInformes() {
        initComponents();
          pack();
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Generar informes");
    controlarJavaHelp.inicializarAyuda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBotonesGenerar = new javax.swing.JPanel();
        bInforme1 = new javax.swing.JButton();
        bInforme3 = new javax.swing.JButton();
        bInforme2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chPDF = new javax.swing.JCheckBox();
        chHTML = new javax.swing.JCheckBox();
        mbAyuda = new javax.swing.JMenuBar();
        mAyuda = new javax.swing.JMenu();
        jmAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bInforme1.setText("Eventos agrupado por tipos de eventos.");
        bInforme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInforme1ActionPerformed(evt);
            }
        });

        bInforme2.setText("Usuarios por cada evento");

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        jLabel1.setText("INFORMES");

        javax.swing.GroupLayout pBotonesGenerarLayout = new javax.swing.GroupLayout(pBotonesGenerar);
        pBotonesGenerar.setLayout(pBotonesGenerarLayout);
        pBotonesGenerarLayout.setHorizontalGroup(
            pBotonesGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBotonesGenerarLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(pBotonesGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBotonesGenerarLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBotonesGenerarLayout.createSequentialGroup()
                        .addGroup(pBotonesGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bInforme2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bInforme3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bInforme1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87))))
        );
        pBotonesGenerarLayout.setVerticalGroup(
            pBotonesGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBotonesGenerarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(bInforme1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bInforme2)
                .addGap(7, 7, 7)
                .addComponent(bInforme3)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        chPDF.setText("PDF");
        chPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chPDFActionPerformed(evt);
            }
        });

        chHTML.setText("HTML");
        chHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chHTMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(chPDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chHTML)
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chPDF)
                    .addComponent(chHTML))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        mAyuda.setText("Ayuda");

        jmAyuda.setText("JavaHelp");
        jmAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAyudaActionPerformed(evt);
            }
        });
        mAyuda.add(jmAyuda);

        mbAyuda.add(mAyuda);

        setJMenuBar(mbAyuda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pBotonesGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pBotonesGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chPDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chPDFActionPerformed

    private void chHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chHTMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chHTMLActionPerformed

    private void jmAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAyudaActionPerformed
        // TODO add your handling code here:
        jmAyuda.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
        controlarJavaHelp.mostrarAyuda();
            }
        });
        
    }//GEN-LAST:event_jmAyudaActionPerformed

    private void bInforme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInforme1ActionPerformed
        // TODO add your handling code here:
        
        if (!chPDF.isSelected() && !chHTML.isSelected()) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar al menos una opción de exportación (PDF o HTML).", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Rutas relativas
        String reportSource = "src/informes/reporteEventosTipo.jrxml";
        String reportCompilado = "src/informes/reporteEventosTipo.jasper";
        Map<String, Object> params = new HashMap<>();
        params.put("titulo", "Eventos por cada tipo - Gestión de eventos");

        // Poner la hora en el archivo
        SimpleDateFormat formatter = new SimpleDateFormat("yyyyMMdd_HHmmss");
        String timestamp = formatter.format(new Date());

        // Compilar y cargar el reporte
        File file = new File(reportCompilado);
        if (!file.exists()) {
            JasperCompileManager.compileReportToFile(reportSource, reportCompilado);
        }
        JasperReport reporte = (JasperReport) JRLoader.loadObjectFromFile(reportCompilado);

        // Establecer la conexión a SQLite
        try (Connection conexion = DriverManager.getConnection("jdbc:sqlite:src/basedatos/eventos.db")) {
            JasperPrint miInforme = JasperFillManager.fillReport(reporte, params, conexion);

            // Mostrar vista previa con JasperViewer
            JasperViewer.viewReport(miInforme, false); // false para no cerrar al salir

            // Exportar PDF si está seleccionado
            if (chPDF.isSelected()) {
                String reportDestinoPDF = "src/informes/pdf_" + timestamp + ".pdf";
                JasperExportManager.exportReportToPdfFile(miInforme, reportDestinoPDF);
                JOptionPane.showMessageDialog(this, "Reporte exportado a PDF.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }

            // Exportar HTML si está seleccionado
            if (chHTML.isSelected()) {
                String reportDestinoHTML = "src/informes/html_" + timestamp + ".html";
                JasperExportManager.exportReportToHtmlFile(miInforme, reportDestinoHTML);
                JOptionPane.showMessageDialog(this, "Reporte exportado a HTML.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al generar el informe: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_bInforme1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventInformes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bInforme1;
    private javax.swing.JButton bInforme2;
    private javax.swing.JButton bInforme3;
    private javax.swing.JCheckBox chHTML;
    private javax.swing.JCheckBox chPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmAyuda;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenuBar mbAyuda;
    private javax.swing.JPanel pBotonesGenerar;
    // End of variables declaration//GEN-END:variables
}
